In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("ECOMM DATA.xlsx - Orders.csv")

In [4]:
df

,ROW ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Profit,Order Priority
0,26341,CA-2012-124891,31/7/2012,31/7/2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,933.57,762.1845,Critical
1,26341,IN-2013-77878,5/2/2013,7/2/2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,923.63,-288.7650,Critical
2,25330,IN-2013-71249,17/10/2013,18/10/2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,915.49,919.9710,Medium
3,13524,ES-2013-1579342,28/1/2013,30/1/2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,910.16,-96.5400,Medium
4,47221,SG-2013-4320,5/11/2013,6/11/2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,903.04,311.5200,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2014-62366,19/6/2014,19/6/2014,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,0.01,4.5000,Medium
51286,35398,US-2014-102288,20/6/2014,24/6/2014,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,0.01,-1.1100,Medium
51287,40470,US-2013-155768,2/12/2013,2/12/2013,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,0.01,11.2308,High
51288,9596,MX-2012-140767,18/2/2012,22/2/2012,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,0.00,2.4000,Medium
51289,6147,MX-2012-134460,22/5/2012,26/5/2012,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,0.00,1.8000,High

In [5]:
df.info

<bound method DataFrame.info of        ROW ID         Order ID  Order Date   Ship Date       Ship Mode  \
0       26341   CA-2012-124891   31/7/2012   31/7/2012        Same Day
1       26341    IN-2013-77878    5/2/2013    7/2/2013    Second Class
2       25330    IN-2013-71249  17/10/2013  18/10/2013     First Class
3       13524  ES-2013-1579342   28/1/2013   30/1/2013     First Class
4       47221     SG-2013-4320   5/11/2013   6/11/2013        Same Day
...       ...              ...         ...         ...             ...
51285   29002    IN-2014-62366   19/6/2014   19/6/2014        Same Day
51286   35398   US-2014-102288   20/6/2014   24/6/2014  Standard Class
51287   40470   US-2013-155768   2/12/2013   2/12/2013        Same Day
51288    9596   MX-2012-140767   18/2/2012   22/2/2012  Standard Class
51289    6147   MX-2012-134460   22/5/2012   26/5/2012    Second Class

      Customer ID     Customer Name      Segment           City  \
0        RH-19495       Rick Hansen     Consumer  New York City
1        JR-16210     Justin Ritter    Corporate     Wollongong
2        CR-12730      Craig Reiter     Consumer       Brisbane
3        KM-16375  Katherine Murray  Home Office         Berlin
4         RH-9495       Rick Hansen     Consumer          Dakar
...           ...               ...          ...            ...
51285    KE-16420   Katrina Edelman    Corporate           Kure
51286    ZC-21910  Zuschuss Carroll     Consumer        Houston
51287    LB-16795    Laurel Beltran  Home Office         Oxnard
51288    RB-19795        Ross Baird  Home Office       Valinhos
51289    MC-18100     Mick Crebagga     Consumer       Tipitapa

                 State  ...        Product ID         Category  Sub-Category  \
0             New York  ...   TEC-AC-10003033       Technology   Accessories
1      New South Wales  ...   FUR-CH-10003950        Furniture        Chairs
2           Queensland  ...   TEC-PH-10004664       Technology        Phones
3               Berlin  ...   TEC-PH-10004583       Technology        Phones
4                Dakar  ...  TEC-SHA-10000501       Technology       Copiers
...                ...  ...               ...              ...           ...
51285        Hiroshima  ...   OFF-FA-10000746  Office Supplies     Fasteners
51286            Texas  ...   OFF-AP-10002906  Office Supplies    Appliances
51287       California  ...   OFF-EN-10001219  Office Supplies     Envelopes
51288        São Paulo  ...   OFF-BI-10000806  Office Supplies       Binders
51289          Managua  ...   OFF-PA-10004155  Office Supplies         Paper

                                            Product Name     Sales Quantity  \
0      Plantronics CS510 - Over-the-Head monaural Wir...  2309.650        7
1              Novimex Executive Leather Armchair, Black  3709.395        9
2                      Nokia Smart Phone, with Caller ID  5175.171        9
3                         Motorola Smart Phone, Cordless  2892.510        5
4                         Sharp Wireless Fax, High-Speed  2832.960        8
...                                                  ...       ...      ...
51285                      Advantus Thumb Tacks, 12 Pack    65.100        5
51286  Hoover Replacement Belt for Commercial Guardsm...     0.444        1
51287       #10- 4 1/8" x 9 1/2" Security-Tint Envelopes    22.920        3
51288                            Acco Index Tab, Economy    13.440        2
51289            Eaton Computer Printout Paper, 8.5 x 11    61.380        3

      Discount Shipping Cost    Profit  Order Priority
0          0.0        933.57  762.1845        Critical
1          0.1        923.63 -288.7650        Critical
2          0.1        915.49  919.9710          Medium
3          0.1        910.16  -96.5400          Medium
4          0.0        903.04  311.5200        Critical
...        ...           ...       ...             ...
51285      0.0          0.01    4.5000          Medium
51286      0.8          0.01   -1.1100          Medium
51287      0.0          0.01   11.2308            High
51288      0.0          0.00    2.4000          Medium
51289      0.0          0.00    1.8000            High

[51290 rows x 24 columns]>

In [6]:
df.describe()

,ROW ID,Postal Code,Sales,Quantity,Discount,Shipping Cost,Profit
count,51290.000000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.383857,55190.379428,246.490581,3.476545,0.142908,26.375915,28.610982
std,14806.263170,32063.693350,487.565361,2.278766,0.212280,57.296804,174.340972
min,1.000000,1040.000000,0.444000,1.000000,0.000000,0.000000,-6599.978000
25%,12823.250000,23223.000000,30.758625,2.000000,0.000000,2.610000,0.000000
50%,25645.500000,56430.500000,85.053000,3.000000,0.000000,7.790000,9.240000
75%,38467.750000,90008.000000,251.053200,5.000000,0.200000,24.450000,36.810000
max,51290.000000,99301.000000,22638.480000,14.000000,0.850000,933.570000,8399.976000

In [7]:
df.head()

,ROW ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Profit,Order Priority
0,26341,CA-2012-124891,31/7/2012,31/7/2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,933.57,762.1845,Critical
1,26341,IN-2013-77878,5/2/2013,7/2/2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,923.63,-288.7650,Critical
2,25330,IN-2013-71249,17/10/2013,18/10/2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,915.49,919.9710,Medium
3,13524,ES-2013-1579342,28/1/2013,30/1/2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,910.16,-96.5400,Medium
4,47221,SG-2013-4320,5/11/2013,6/11/2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,903.04,311.5200,Critical

In [8]:
df.tail()

,ROW ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Profit,Order Priority
51285,29002,IN-2014-62366,19/6/2014,19/6/2014,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,0.01,4.5000,Medium
51286,35398,US-2014-102288,20/6/2014,24/6/2014,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,0.01,-1.1100,Medium
51287,40470,US-2013-155768,2/12/2013,2/12/2013,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,0.01,11.2308,High
51288,9596,MX-2012-140767,18/2/2012,22/2/2012,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,0.00,2.4000,Medium
51289,6147,MX-2012-134460,22/5/2012,26/5/2012,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,0.00,1.8000,High

In [9]:
df.isnull()

,ROW ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Profit,Order Priority
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51286,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51287,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51288,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51289,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [10]:
df.isnull().sum()

ROW ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Market                0
Postal Code       41296
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Shipping Cost         0
Profit                0
Order Priority        0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.drop_duplicates()

,ROW ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Profit,Order Priority
0,26341,CA-2012-124891,31/7/2012,31/7/2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,933.57,762.1845,Critical
1,26341,IN-2013-77878,5/2/2013,7/2/2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,923.63,-288.7650,Critical
2,25330,IN-2013-71249,17/10/2013,18/10/2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,915.49,919.9710,Medium
3,13524,ES-2013-1579342,28/1/2013,30/1/2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,910.16,-96.5400,Medium
4,47221,SG-2013-4320,5/11/2013,6/11/2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,903.04,311.5200,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2014-62366,19/6/2014,19/6/2014,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,0.01,4.5000,Medium
51286,35398,US-2014-102288,20/6/2014,24/6/2014,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,0.01,-1.1100,Medium
51287,40470,US-2013-155768,2/12/2013,2/12/2013,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,0.01,11.2308,High
51288,9596,MX-2012-140767,18/2/2012,22/2/2012,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,0.00,2.4000,Medium
51289,6147,MX-2012-134460,22/5/2012,26/5/2012,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,0.00,1.8000,High

In [13]:
df.dropna()

,ROW ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Profit,Order Priority
0,26341,CA-2012-124891,31/7/2012,31/7/2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,933.57,762.1845,Critical
8,40155,CA-2014-135909,14/10/2014,21/10/2014,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.960,5,0.2,867.69,1906.4850,Low
9,40936,CA-2012-116638,28/1/2012,31/1/2012,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,865.74,-1862.3124,Critical
10,34577,CA-2011-102988,5/4/2011,9/4/2011,Second Class,GM-14695,Greg Maxwell,Corporate,Alexandria,Virginia,...,OFF-SU-10002881,Office Supplies,Supplies,Martin Yale Chadless Opener Electric Letter Op...,4164.050,5,0.0,846.54,83.2810,High
16,36178,CA-2014-143567,3/11/2014,6/11/2014,Second Class,TB-21175,Thomas Boland,Corporate,Henderson,Kentucky,...,TEC-AC-10004145,Technology,Accessories,Logitech diNovo Edge Keyboard,2249.910,9,0.0,780.70,517.4793,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51270,38414,CA-2011-143168,18/10/2011,23/10/2011,Second Class,IG-15085,Ivan Gibson,Consumer,Seattle,Washington,...,OFF-BI-10003784,Office Supplies,Binders,Computer Printout Index Tabs,1.344,1,0.2,0.03,0.4704,Medium
51276,31558,US-2014-155299,9/6/2014,13/6/2014,Standard Class,Dl-13600,Dorris liebe,Corporate,Pasadena,Texas,...,OFF-AP-10002203,Office Supplies,Appliances,Eureka Disposable Bags for Sanitaire Vibra Gro...,1.624,2,0.8,0.02,-4.4660,Medium
51277,37361,CA-2012-111780,25/12/2012,30/12/2012,Second Class,RA-19285,Ralph Arnett,Consumer,San Diego,California,...,OFF-PA-10001667,Office Supplies,Paper,Great White Multi-Use Recycled Paper (20Lb. an...,17.940,3,0.0,0.02,8.0730,High
51286,35398,US-2014-102288,20/6/2014,24/6/2014,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,0.01,-1.1100,Medium
51287,40470,US-2013-155768,2/12/2013,2/12/2013,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,0.01,11.2308,High

In [14]:
df.to_excel

<bound method NDFrame.to_excel of        ROW ID         Order ID  Order Date   Ship Date       Ship Mode  \
0       26341   CA-2012-124891   31/7/2012   31/7/2012        Same Day
1       26341    IN-2013-77878    5/2/2013    7/2/2013    Second Class
2       25330    IN-2013-71249  17/10/2013  18/10/2013     First Class
3       13524  ES-2013-1579342   28/1/2013   30/1/2013     First Class
4       47221     SG-2013-4320   5/11/2013   6/11/2013        Same Day
...       ...              ...         ...         ...             ...
51285   29002    IN-2014-62366   19/6/2014   19/6/2014        Same Day
51286   35398   US-2014-102288   20/6/2014   24/6/2014  Standard Class
51287   40470   US-2013-155768   2/12/2013   2/12/2013        Same Day
51288    9596   MX-2012-140767   18/2/2012   22/2/2012  Standard Class
51289    6147   MX-2012-134460   22/5/2012   26/5/2012    Second Class

      Customer ID     Customer Name      Segment           City  \
0        RH-19495       Rick Hansen     Consumer  New York City
1        JR-16210     Justin Ritter    Corporate     Wollongong
2        CR-12730      Craig Reiter     Consumer       Brisbane
3        KM-16375  Katherine Murray  Home Office         Berlin
4         RH-9495       Rick Hansen     Consumer          Dakar
...           ...               ...          ...            ...
51285    KE-16420   Katrina Edelman    Corporate           Kure
51286    ZC-21910  Zuschuss Carroll     Consumer        Houston
51287    LB-16795    Laurel Beltran  Home Office         Oxnard
51288    RB-19795        Ross Baird  Home Office       Valinhos
51289    MC-18100     Mick Crebagga     Consumer       Tipitapa

                 State  ...        Product ID         Category  Sub-Category  \
0             New York  ...   TEC-AC-10003033       Technology   Accessories
1      New South Wales  ...   FUR-CH-10003950        Furniture        Chairs
2           Queensland  ...   TEC-PH-10004664       Technology        Phones
3               Berlin  ...   TEC-PH-10004583       Technology        Phones
4                Dakar  ...  TEC-SHA-10000501       Technology       Copiers
...                ...  ...               ...              ...           ...
51285        Hiroshima  ...   OFF-FA-10000746  Office Supplies     Fasteners
51286            Texas  ...   OFF-AP-10002906  Office Supplies    Appliances
51287       California  ...   OFF-EN-10001219  Office Supplies     Envelopes
51288        São Paulo  ...   OFF-BI-10000806  Office Supplies       Binders
51289          Managua  ...   OFF-PA-10004155  Office Supplies         Paper

                                            Product Name     Sales Quantity  \
0      Plantronics CS510 - Over-the-Head monaural Wir...  2309.650        7
1              Novimex Executive Leather Armchair, Black  3709.395        9
2                      Nokia Smart Phone, with Caller ID  5175.171        9
3                         Motorola Smart Phone, Cordless  2892.510        5
4                         Sharp Wireless Fax, High-Speed  2832.960        8
...                                                  ...       ...      ...
51285                      Advantus Thumb Tacks, 12 Pack    65.100        5
51286  Hoover Replacement Belt for Commercial Guardsm...     0.444        1
51287       #10- 4 1/8" x 9 1/2" Security-Tint Envelopes    22.920        3
51288                            Acco Index Tab, Economy    13.440        2
51289            Eaton Computer Printout Paper, 8.5 x 11    61.380        3

      Discount Shipping Cost    Profit  Order Priority
0          0.0        933.57  762.1845        Critical
1          0.1        923.63 -288.7650        Critical
2          0.1        915.49  919.9710          Medium
3          0.1        910.16  -96.5400          Medium
4          0.0        903.04  311.5200        Critical
...        ...           ...       ...             ...
51285      0.0          0.01    4.5000          Medium
51286      0.8          0.01   -1.1100          Medium
51287      0.0          0.01   11.2308            High
51288      0.0          0.00    2.4000          Medium
51289      0.0          0.00    1.8000            High

[51290 rows x 24 columns]>

In [19]:
product_id = df["Product ID"]

In [20]:
product_id

0         TEC-AC-10003033
1         FUR-CH-10003950
2         TEC-PH-10004664
3         TEC-PH-10004583
4        TEC-SHA-10000501
               ...
51285     OFF-FA-10000746
51286     OFF-AP-10002906
51287     OFF-EN-10001219
51288     OFF-BI-10000806
51289     OFF-PA-10004155
Name: Product ID, Length: 51290, dtype: object

In [22]:
for i in range(0, len(product_id)):
    if i%2==0:
        print(i," ",product_id[i])

0   TEC-AC-10003033
2   TEC-PH-10004664
4   TEC-SHA-10000501
6   FUR-CH-10004050
8   OFF-BI-10003527
10   OFF-SU-10002881
12   TEC-CIS-10001717
14   OFF-AP-10003500
16   TEC-AC-10004145
18   TEC-CO-10000865
20   FUR-HON-10000224
22   FUR-CH-10000027
24   TEC-PH-10004182
26   FUR-TA-10004744
28   TEC-PH-10002885
30   TEC-PH-10002815
32   FUR-CH-10002024
34   FUR-TA-10003473
36   TEC-MA-10003979
38   TEC-CO-10000013
40   TEC-PH-10000499
42   FUR-BO-10004852
44   OFF-AP-10000486
46   FUR-CH-10003365
48   TEC-MA-10002680
50   OFF-BI-10003527
52   TEC-CO-10001449
54   TEC-MOT-10002272
56   TEC-CO-10001766
58   OFF-AP-10002244
60   FUR-BO-10001073
62   TEC-PH-10002035
64   FUR-CH-10000027
66   FUR-BO-10004999
68   TEC-PH-10004196
70   FUR-CH-10003232
72   FUR-HAR-10002873
74   TEC-PH-10004505
76   OFF-BI-10003527
78   TEC-CO-10002526
80   FUR-CH-10002891
82   OFF-BI-10004995
84   TEC-PH-10004327
86   OFF-HOO-10001881
88   FUR-BO-10003282
90   TEC-PH-10004664
92   OFF-AP-10002552
94   FUR-CH-10001415
96   FUR-BO-10001133
98   TEC-MA-10003515
100   TEC-MOT-10003348
102   TEC-PH-10002898
104   TEC-CO-10001633
106   FUR-TA-10004575
108   OFF-AP-10003598
110   TEC-MA-10001047
112   FUR-BO-10002003
114   OFF-AP-10000647
116   TEC-CO-10001926
118   FUR-CH-10002203
120   TEC-CO-10000562
122   OFF-BI-10000545
124   TEC-CO-10004099
126   FUR-TA-10001932
128   FUR-CH-10000749
130   TEC-CO-10004535
132   FUR-BO-10001212
134   FUR-CH-10001215
136   OFF-AP-10001776
138   FUR-CH-10001854
140   TEC-AC-10000376
142   TEC-SAM-10004230
144   OFF-AP-10002312
146   TEC-CO-10000865
148   FUR-BO-10000288
150   OFF-AP-10001623
152   TEC-CO-10004365
154   TEC-PH-10000499
156   FUR-BO-10004834
158   TEC-MA-10003979
160   OFF-AP-10002090
162   TEC-CIS-10002344
164   OFF-AP-10004964
166   FUR-BO-10004679
168   TEC-PH-10002759
170   FUR-BO-10001934
172   TEC-PH-10001699
174   FUR-TA-10001889
176   TEC-PH-10000018
178   TEC-AC-10001949
180   OFF-HOO-10004910
182   FUR-TA-10000347
184   OFF-AP-10002090
186   FUR-TA-10003596
188   FUR-TA-10003179
190   FUR-TA-10003078
192   FUR-TA-10000184
194   OFF-AP-10001956
196   OFF-AP-10003382
198   OFF-AP-10003917
200   TEC-CO-10003819
202   FUR-BO-10003404
204   OFF-SME-10000746
206   TEC-MA-10003673
208   TEC-PH-10004196
210   TEC-CO-10000208
212   FUR-CH-10003312
214   OFF-ST-10004060
216   FUR-BO-10002708
218   FUR-BO-10001192
220   FUR-SAU-10002255
222   TEC-CO-10001954
224   TEC-PH-10003856
226   FUR-CH-10000974
228   FUR-CH-10003616
230   FUR-CH-10000479
232   OFF-SU-10002881
234   TEC-NOK-10001283
236   OFF-BI-10001359
238   FUR-CH-10002335
240   TEC-PH-10001459
242   FUR-BO-10002444
244   TEC-MA-10004772
246   TEC-CO-10002911
248   TEC-PH-10000169
250   TEC-CO-10002526
252   TEC-NOK-10004339
254   FUR-TA-10002153
256   OFF-AP-10002681
258   TEC-AC-10002049
260   OFF-AP-10004627
262   TEC-PH-10001457
264   FUR-BO-10003991
266   OFF-AP-10002793
268   FUR-BO-10003103
270   TEC-CO-10002040
272   OFF-AP-10002397
274   FUR-CH-10001207
276   FUR-CH-10003232
278   TEC-CO-10002617
280   FUR-CH-10003232
282   TEC-HEW-10003460
284   TEC-PH-10002672
286   OFF-AP-10003057
288   TEC-CO-10002095
290   TEC-CO-10004722
292   TEC-PH-10004182
294   OFF-HOO-10000335
296   FUR-BO-10001372
298   OFF-ST-10004597
300   OFF-AP-10003240
302   TEC-MOT-10003348
304   FUR-BO-10002866
306   FUR-TA-10001276
308   TEC-APP-10002966
310   FUR-CH-10000685
312   TEC-CO-10003931
314   FUR-BO-10001553
316   OFF-AP-10000540
318   FUR-BO-10001749
320   FUR-BO-10001934
322   TEC-MA-10000864
324   FUR-CH-10000602
326   TEC-CO-10003763
328   FUR-IKE-10001539
330   TEC-CO-10002376
332   OFF-AP-10000136
334   FUR-BO-10001471
336   TEC-PH-10004505
338   OFF-ST-10004191
340   FUR-OFF-10001224
342   OFF-AP-10004913
344   TEC-MA-10000822
346   FUR-TA-10003222
348   TEC-PH-10002885
350   FUR-TA-10003354
352   OFF-BI-10003091
354   TEC-SAM-10004940
356   OFF-AP-10001169
358   TEC-CO-10002095
360   TEC-CO-10001449
362   TEC-PH-10002991
364   TEC-CO-10004567
366   TEC-CO-10003448
368   OFF-ST-10003150
370   FUR-CH-10004694
372   TEC-CO-10001818
374   FUR-BO-10001196
376   FUR-CH-10003616
378   TEC-MA-10000753
380   TEC-PH-10001457
382   TEC-PH-10002601
384   OFF-ROG-10001735
386   TEC-CO-10001413
388   FUR-LES-10002026
390   OFF-ST-10004459
392   TEC-PH-10000499
394   FUR-BO-10002580
396   OFF-ROG-10001101
398   FUR-CH-10000660
400   OFF-ST-10003741
402   FUR-TA-10001116
404   TEC-CO-10004997
406   FUR-CH-10002780
408   TEC-CO-10002376
410   TEC-PH-10000106
412   TEC-CO-10003342
414   FUR-BEV-10004919
416   TEC-OKI-10001385
418   FUR-BO-10002613
420   OFF-AP-10001931
422   TEC-CO-10002150
424   FUR-CH-10000051
426   TEC-CIS-10002259
428   TEC-PH-10001795
430   OFF-AP-10002681
432   TEC-PH-10003457
434   TEC-AC-10001838
436   TEC-AC-10004571
438   FUR-BO-10001212
440   OFF-KIT-10003683
442   FUR-BO-10000980
444   TEC-PH-10000730
446   OFF-AP-10002321
448   TEC-PH-10001396
450   TEC-MEM-10002202
452   TEC-SHA-10001231
454   FUR-BO-10000980
456   OFF-AP-10002252
458   TEC-BRO-10004802
460   TEC-CO-10003102
462   FUR-BO-10000967
464   TEC-SHA-10000971
466   FUR-CH-10000546
468   OFF-AP-10004964
470   OFF-AP-10002573
472   FUR-CH-10002061
474   OFF-AP-10001623
476   FUR-BO-10002990
478   OFF-AP-10002793
480   TEC-PH-10000720
482   OFF-SME-10000538
484   OFF-CUI-10000682
486   TEC-AC-10002244
488   FUR-BO-10004852
490   FUR-TA-10003954
492   OFF-AP-10001593
494   TEC-MEM-10002005
496   TEC-MA-10002428
498   FUR-CH-10001271
500   TEC-PH-10000018
502   FUR-CH-10001332
504   TEC-PH-10001699
506   OFF-ST-10000704
508   TEC-MA-10002918
510   OFF-SU-10002881
512   OFF-AP-10001623
514   TEC-PH-10004006
516   OFF-AP-10003275
518   TEC-MA-10000488
520   TEC-CO-10001046
522   TEC-CAN-10000932
524   TEC-MOT-10003348
526   OFF-AP-10001329
528   TEC-PH-10001751
530   OFF-AP-10003558
532   FUR-TA-10002101
534   FUR-TA-10001494
536   TEC-CO-10000562
538   TEC-MA-10000488
540   FUR-BO-10003103
542   TEC-AC-10004849
544   OFF-AP-10001106
546   TEC-CIS-10002344
548   FUR-TA-10002533
550   FUR-BO-10004043
552   FUR-TA-10003954
554   TEC-MA-10002927
556   TEC-CO-10001449
558   TEC-CO-10000971
560   FUR-TA-10003748
562   TEC-MA-10002468
564   OFF-BRE-10002706
566   OFF-AP-10004201
568   TEC-AC-10004145
570   TEC-CO-10004089
572   OFF-AP-10000675
574   OFF-BI-10001359
576   OFF-HAM-10004896
578   TEC-AC-10003506
580   OFF-AP-10003598
582   FUR-BO-10004472
584   TEC-PH-10001066
586   FUR-TA-10003569
588   TEC-CO-10002035
590   FUR-SAU-10001776
592   TEC-CO-10000660
594   OFF-ST-10001478
596   OFF-AP-10003275
598   OFF-AP-10004031
600   TEC-AC-10001566
602   OFF-BI-10003527
604   TEC-CIS-10001938
606   OFF-SU-10002881
608   OFF-AP-10001623
610   TEC-CO-10002283
612   TEC-PH-10001751
614   FUR-CH-10004675
616   TEC-MA-10004609
618   OFF-AP-10002945
620   FUR-TA-10002786
622   TEC-PH-10003513
624   TEC-AC-10000203
626   FUR-CH-10003981
628   FUR-CH-10002250
630   TEC-PH-10003683
632   TEC-MOT-10000554
634   FUR-BO-10001749
636   TEC-PH-10000037
638   OFF-SU-10000076
640   OFF-AP-10003032
642   TEC-PH-10002962
644   FUR-CH-10002585
646   TEC-MA-10003557
648   OFF-AP-10003795
650   TEC-CO-10001449
652   TEC-CO-10001839
654   TEC-CO-10003763
656   TEC-CO-10000137
658   TEC-PH-10004910
660   FUR-BO-10004844
662   TEC-AC-10003265
664   OFF-AP-10002945
666   FUR-CH-10000885
668   TEC-PH-10000169
670   OFF-AP-10001776
672   TEC-AC-10004145
674   FUR-BO-10002462
676   FUR-BO-10003282
678   TEC-PH-10000780
680   TEC-PH-10002815
682   TEC-MA-10004655
684   TEC-CO-10002040
686   FUR-TA-10002467
688   TEC-PH-10002549
690   TEC-BEL-10003985
692   OFF-BI-10001359
694   FUR-CH-10002573
696   FUR-BUS-10004820
698   FUR-CH-10003981
700   OFF-AP-10003287
702   TEC-CO-10001678
704   FUR-BO-10004679
706   FUR-CHR-10002165
708   FUR-BO-10004834
710   FUR-CH-10000974
712   OFF-AP-10000647
714   OFF-AP-10003217
716   TEC-PH-10003492
718   TEC-PH-10004977
720   OFF-AP-10004512
722   TEC-CO-10003262
724   FUR-BO-10003282
726   FUR-BO-10003126
728   TEC-MOT-10002560
730   TEC-CIS-10002344
732   TEC-PH-10000214
734   TEC-CO-10001222
736   TEC-CO-10000972
738   FUR-TA-10002497
740   FUR-TA-10003569
742   TEC-PAN-10000577
744   FUR-BO-10001392
746   FUR-TA-10003473
748   TEC-CO-10001008
750   FUR-CH-10004910
752   FUR-BO-10003734
754   OFF-AP-10001018
756   TEC-CO-10001375
758   TEC-PH-10001795
760   FUR-BO-10003738
762   FUR-SAF-10002112
764   TEC-AC-10002049
766   FUR-TA-10002650
768   TEC-PH-10004182
770   TEC-PH-10002652
772   TEC-AC-10004938
774   TEC-KON-10002052
776   TEC-MA-10004446
778   OFF-ST-10003208
780   FUR-TA-10002411
782   TEC-PH-10000780
784   FUR-BUS-10001781
786   TEC-PH-10003560
788   TEC-MA-10000433
790   TEC-PH-10001670
792   FUR-BO-10004834
794   FUR-TA-10004524
796   TEC-PH-10004539
798   FUR-TA-10001950
800   FUR-TA-10000226
802   FUR-SAF-10003469
804   FUR-CH-10002250
806   TEC-MA-10003780
808   FUR-TA-10001360
810   TEC-CO-10001449
812   FUR-BO-10004043
814   TEC-MA-10000606
816   TEC-BRO-10000374
818   FUR-TA-10004619
820   OFF-AP-10004183
822   TEC-PH-10003713
824   OFF-ST-10002743
826   TEC-MA-10004502
828   TEC-SAM-10000765
830   TEC-CO-10004404
832   TEC-MA-10004534
834   OFF-AP-10002534
836   FUR-BO-10004630
838   TEC-CO-10002095
840   TEC-CO-10002095
842   FUR-BO-10000666
844   TEC-MA-10003400
846   OFF-ST-10004315
848   TEC-MA-10003557
850   OFF-ST-10003785
852   TEC-AC-10002719
854   TEC-KON-10000837
856   FUR-CH-10002780
858   TEC-CO-10000447
860   TEC-CO-10002009
862   OFF-ST-10003306
864   FUR-CH-10002331
866   TEC-CO-10004202
868   FUR-BO-10000160
870   FUR-BO-10004218
872   FUR-CH-10000783
874   TEC-MEM-10002005
876   FUR-CH-10004983
878   FUR-CH-10001897
880   TEC-CO-10001192
882   FUR-TA-10004744
884   OFF-AP-10000437
886   OFF-AP-10003057
888   TEC-CO-10002376
890   TEC-CO-10003019
892   FUR-TA-10001786
894   TEC-PH-10004057
896   TEC-PH-10003713
898   FUR-CH-10003941
900   FUR-BO-10004053
902   OFF-AP-10002945
904   TEC-CO-10003784
906   FUR-IKE-10001312
908   FUR-BO-10004541
910   TEC-PH-10004823
912   FUR-BO-10004707
914   TEC-CO-10004662
916   TEC-CO-10001654
918   TEC-AC-10001908
920   TEC-CO-10000794
922   OFF-AP-10003834
924   FUR-BO-10002892
926   TEC-CO-10004567
928   OFF-AP-10001593
930   OFF-AP-10001931
932   TEC-CAN-10004839
934   TEC-MA-10003078
936   OFF-ST-10001547
938   TEC-MA-10004929
940   FUR-BUS-10001243
942   OFF-BI-10001359
944   FUR-CH-10002573
946   TEC-PH-10002742
948   TEC-MA-10004772
950   TEC-MA-10003353
952   TEC-PH-10002815
954   TEC-CAN-10004913
956   TEC-PH-10001459
958   FUR-TA-10000207
960   FUR-TA-10003527
962   TEC-CIS-10000436
964   TEC-CO-10001626
966   TEC-PH-10000419
968   OFF-AP-10001190
970   TEC-HEW-10001074
972   FUR-TA-10001786
974   FUR-CH-10003973
976   TEC-CO-10001046
978   FUR-TA-10004820
980   FUR-TA-10002433
982   TEC-CO-10001162
984   TEC-PH-10002597
986   TEC-CO-10000967
988   FUR-TA-10001496
990   OFF-BI-10003091
992   OFF-BI-10003925
994   TEC-CIS-10001717
996   OFF-AP-10002518
998   FUR-BO-10002766
1000   FUR-CH-10003841
1002   TEC-BRO-10002103
1004   FUR-CH-10002247
1006   FUR-CH-10002247
1008   TEC-PH-10000984
1010   FUR-CH-10002944
1012   OFF-ST-10002292
1014   FUR-SAF-10001136
1016   OFF-ST-10002395
1018   TEC-MA-10000697
1020   FUR-CH-10000527
1022   FUR-BO-10000596
1024   FUR-DAN-10002348
1026   OFF-AP-10001178
1028   TEC-MA-10002073
1030   TEC-MA-10001627
1032   TEC-CO-10001204
1034   FUR-TA-10004306
1036   FUR-DAN-10004510
1038   TEC-HEW-10003695
1040   TEC-PH-10000879
1042   TEC-PH-10004074
1044   TEC-AC-10002914
1046   OFF-ST-10000362
1048   FUR-CH-10001492
1050   TEC-CO-10004662
1052   FUR-BO-10000002
1054   FUR-TA-10000989
1056   OFF-AP-10002351
1058   TEC-MA-10002910
1060   FUR-LES-10004886
1062   FUR-BO-10000259
1064   OFF-ST-10003716
1066   OFF-ST-10003306
1068   TEC-PH-10003580
1070   FUR-CH-10000027
1072   TEC-PAN-10000377
1074   FUR-CH-10000981
1076   OFF-ST-10002555
1078   OFF-ELD-10000845
1080   OFF-ST-10003295
1082   TEC-PH-10000030
1084   TEC-CO-10003087
1086   TEC-PH-10002683
1088   TEC-CO-10002240
1090   TEC-PH-10001289
1092   FUR-CH-10002247
1094   OFF-AP-10002904
1096   TEC-AC-10003666
1098   FUR-BO-10001405
1100   TEC-MA-10000112
1102   OFF-AP-10002518
1104   FUR-BO-10001196
1106   TEC-CO-10002232
1108   OFF-AP-10004295
1110   OFF-AP-10004245
1112   FUR-CH-10004255
1114   OFF-ST-10004597
1116   TEC-CO-10001342
1118   FUR-CH-10002061
1120   FUR-BO-10003554
1122   FUR-IKE-10002147
1124   TEC-CIS-10002259
1126   FUR-CH-10001207
1128   TEC-EPS-10004558
1130   OFF-ST-10003153
1132   FUR-BO-10002510
1134   TEC-CO-10001630
1136   TEC-MA-10003326
1138   FUR-BO-10004771
1140   TEC-MA-10004587
1142   TEC-MA-10000161
1144   TEC-CO-10000771
1146   OFF-ST-10000078
1148   TEC-CO-10001678
1150   OFF-AP-10000335
1152   TEC-CO-10001893
1154   TEC-CO-10002119
1156   FUR-CH-10002213
1158   FUR-BO-10002277
1160   TEC-CO-10000266
1162   TEC-CO-10002313
1164   FUR-BO-10001471
1166   FUR-BO-10001039
1168   FUR-CH-10000343
1170   FUR-CH-10000513
1172   OFF-ST-10002555
1174   FUR-CH-10003950
1176   FUR-CH-10003861
1178   TEC-HEW-10003829
1180   FUR-CH-10000430
1182   TEC-CO-10001654
1184   FUR-CH-10000777
1186   OFF-AP-10003794
1188   TEC-CO-10000967
1190   TEC-CO-10001633
1192   OFF-ST-10000103
1194   TEC-MEM-10004014
1196   TEC-CO-10001309
1198   TEC-PH-10004823
1200   FUR-TA-10003164
1202   FUR-BO-10004630
1204   OFF-AP-10003917
1206   TEC-HP -10003345
1208   TEC-CO-10001191
1210   FUR-BO-10004660
1212   FUR-BO-10003541
1214   FUR-BO-10004852
1216   FUR-CH-10000660
1218   TEC-PH-10001699
1220   FUR-BO-10000891
1222   TEC-AC-10002049
1224   FUR-IKE-10001312
1226   TEC-PH-10002774
1228   FUR-BO-10003499
1230   FUR-CH-10000994
1232   FUR-TA-10003319
1234   TEC-CO-10002493
1236   OFF-AR-10004825
1238   TEC-MA-10002316
1240   FUR-BO-10001934
1242   OFF-BI-10000545
1244   FUR-CH-10004255
1246   TEC-PH-10000896
1248   TEC-CO-10002379
1250   TEC-CO-10001919
1252   TEC-NOK-10001283
1254   OFF-ST-10004459
1256   TEC-CAN-10001437
1258   TEC-CIS-10002259
1260   FUR-BO-10002031
1262   FUR-CH-10000258
1264   TEC-AC-10001539
1266   FUR-CH-10004199
1268   TEC-PH-10003811
1270   OFF-ST-10004381
1272   TEC-CO-10000972
1274   TEC-CO-10000266
1276   TEC-PH-10002806
1278   FUR-BO-10001073
1280   OFF-CUI-10002022
1282   OFF-HAM-10000983
1284   FUR-CH-10000777
1286   TEC-PH-10002904
1288   FUR-CH-10001429
1290   TEC-HEW-10001074
1292   FUR-CH-10000430
1294   TEC-MA-10002080
1296   TEC-MA-10001881
1298   TEC-MA-10001261
1300   FUR-CH-10001322
1302   TEC-MA-10001494
1304   TEC-PH-10001284
1306   TEC-AC-10001486
1308   FUR-BO-10001390
1310   TEC-AC-10003955
1312   TEC-AC-10003832
1314   TEC-CO-10002659
1316   FUR-BO-10002383
1318   TEC-SAM-10003493
1320   TEC-AC-10001410
1322   TEC-CO-10002678
1324   TEC-MA-10004421
1326   TEC-EPS-10004965
1328   TEC-PH-10004505
1330   FUR-CH-10001726
1332   OFF-ST-10003306
1334   TEC-PH-10004281
1336   FUR-DAN-10002314
1338   FUR-BO-10004529
1340   TEC-CO-10003158
1342   OFF-ST-10000695
1344   TEC-MA-10003927
1346   TEC-MOT-10003366
1348   OFF-AP-10001041
1350   TEC-PH-10002660
1352   TEC-AC-10000053
1354   TEC-AC-10000639
1356   OFF-TEN-10000025
1358   FUR-CH-10000027
1360   FUR-CH-10003054
1362   TEC-PH-10001284
1364   TEC-CO-10003694
1366   FUR-BO-10000279
1368   TEC-MOT-10000554
1370   TEC-AC-10000203
1372   TEC-CO-10003448
1374   FUR-CH-10002250
1376   TEC-HEW-10002304
1378   FUR-TA-10003929
1380   TEC-CO-10003917
1382   OFF-BI-10004995
1384   OFF-AP-10002998
1386   TEC-CO-10001192
1388   OFF-BI-10004584
1390   FUR-CH-10000891
1392   TEC-PH-10004626
1394   TEC-PH-10001117
1396   OFF-AP-10001931
1398   FUR-BO-10000699
1400   OFF-AP-10003511
1402   TEC-CO-10002796
1404   FUR-CH-10002610
1406   TEC-CO-10002197
1408   OFF-AP-10003497
1410   TEC-PH-10003762
1412   FUR-TA-10002972
1414   TEC-MA-10000982
1416   TEC-CO-10002601
1418   OFF-AP-10000329
1420   TEC-STA-10003447
1422   FUR-BO-10004142
1424   FUR-CH-10002247
1426   FUR-TA-10003583
1428   TEC-CO-10001264
1430   OFF-ST-10004060
1432   FUR-CH-10001854
1434   TEC-AC-10001258
1436   FUR-BO-10002003
1438   FUR-CH-10003950
1440   OFF-ST-10002615
1442   OFF-HAM-10004674
1444   FUR-BO-10000243
1446   FUR-BO-10003779
1448   OFF-ST-10003931
1450   OFF-AP-10000667
1452   OFF-FEL-10001405
1454   OFF-AP-10000423
1456   OFF-ST-10003455
1458   TEC-PH-10003794
1460   OFF-AP-10000891
1462   TEC-CO-10000620
1464   OFF-AP-10000800
1466   TEC-NOK-10001283
1468   OFF-ST-10003785
1470   OFF-BI-10004600
1472   OFF-ST-10004381
1474   FUR-TA-10000052
1476   FUR-SAF-10004252
1478   FUR-TA-10003003
1480   OFF-AP-10001406
1482   OFF-AP-10003779
1484   OFF-CUI-10000105
1486   TEC-AC-10001995
1488   TEC-MOT-10000939
1490   FUR-TA-10003747
1492   FUR-TA-10001786
1494   FUR-CH-10004669
1496   FUR-TA-10000649
1498   FUR-BO-10004648
1500   FUR-BO-10003320
1502   FUR-CH-10000454
1504   TEC-PH-10002042
1506   TEC-PH-10002332
1508   FUR-CH-10004609
1510   TEC-PH-10001670
1512   OFF-ST-10003295
1514   TEC-MA-10003515
1516   FUR-BO-10004679
1518   TEC-MA-10002178
1520   TEC-PH-10000493
1522   OFF-KIT-10001213
1524   TEC-CO-10003142
1526   TEC-CAN-10004291
1528   FUR-CH-10003746
1530   TEC-SHA-10001309
1532   TEC-PH-10004680
1534   TEC-CO-10003951
1536   TEC-MA-10003801
1538   FUR-CH-10003354
1540   FUR-BO-10004771
1542   FUR-CH-10002991
1544   OFF-ROG-10000191
1546   OFF-ST-10003805
1548   TEC-PH-10001457
1550   TEC-PH-10000800
1552   FUR-CH-10003009
1554   FUR-BO-10001324
1556   TEC-CO-10004831
1558   FUR-CH-10000885
1560   TEC-CO-10002174
1562   TEC-PH-10001457
1564   TEC-AC-10002122
1566   FUR-CH-10002880
1568   TEC-CO-10000405
1570   OFF-AP-10001670
1572   TEC-PH-10002310
1574   OFF-ST-10000439
1576   OFF-ST-10003208
1578   FUR-CH-10003950
1580   FUR-CH-10002090
1582   OFF-AP-10003917
1584   FUR-BO-10004911
1586   FUR-BO-10001811
1588   FUR-BO-10001216
1590   TEC-ENE-10004627
1592   TEC-BRO-10004802
1594   TEC-PH-10001079
1596   TEC-PH-10000780
1598   TEC-MA-10004552
1600   TEC-CO-10004997
1602   FUR-CH-10002132
1604   TEC-MA-10002468
1606   FUR-TA-10000665
1608   FUR-CH-10002250
1610   TEC-PH-10001585
1612   OFF-ST-10003837
1614   FUR-TA-10000198
1616   FUR-CH-10004997
1618   OFF-AP-10000864
1620   OFF-ST-10003295
1622   TEC-PH-10002296
1624   FUR-BO-10004340
1626   OFF-ST-10002555
1628   TEC-CO-10003777
1630   TEC-PH-10002320
1632   OFF-AP-10002651
1634   TEC-CAN-10001853
1636   OFF-AP-10001593
1638   OFF-AP-10000672
1640   TEC-AC-10002049
1642   FUR-BO-10002545
1644   TEC-PH-10000018
1646   TEC-PH-10000895
1648   OFF-HAM-10003040
1650   TEC-CO-10004535
1652   TEC-CO-10001008
1654   TEC-MA-10001546
1656   FUR-BO-10004508
1658   TEC-CO-10002313
1660   OFF-BI-10003718
1662   OFF-AP-10004183
1664   TEC-MA-10004669
1666   TEC-PH-10000270
1668   FUR-BO-10000259
1670   TEC-MA-10003624
1672   FUR-FU-10000065
1674   FUR-BO-10000203
1676   OFF-AP-10001322
1678   TEC-CO-10002759
1680   OFF-ST-10001638
1682   FUR-TA-10000805
1684   TEC-EPS-10001651
1686   FUR-TA-10004154
1688   TEC-CO-10000427
1690   FUR-TA-10004336
1692   FUR-CH-10003981
1694   FUR-BO-10002032
1696   FUR-FU-10001942
1698   OFF-AP-10001931
1700   OFF-AP-10001178
1702   OFF-AP-10001293
1704   FUR-SAF-10003819
1706   OFF-TEN-10001480
1708   TEC-PH-10003002
1710   TEC-PH-10001354
1712   FUR-BO-10004806
1714   FUR-CH-10004774
1716   FUR-TA-10003591
1718   TEC-CO-10004701
1720   FUR-TA-10000688
1722   FUR-CH-10000932
1724   FUR-BO-10003301
1726   TEC-CAN-10001437
1728   FUR-CH-10003941
1730   TEC-CO-10000070
1732   OFF-FEL-10002867
1734   FUR-TA-10001205
1736   FUR-HON-10004987
1738   FUR-HON-10001847
1740   TEC-AC-10000483
1742   OFF-AP-10003511
1744   OFF-AP-10000975
1746   TEC-CO-10000137
1748   TEC-CO-10002587
1750   OFF-ST-10000025
1752   TEC-CO-10001343
1754   FUR-BO-10001739
1756   OFF-BI-10004519
1758   FUR-BO-10003028
1760   TEC-PH-10003963
1762   TEC-CO-10002376
1764   OFF-TEN-10000433
1766   TEC-AC-10002244
1768   TEC-CO-10001501
1770   TEC-AC-10004108
1772   FUR-TA-10000671
1774   TEC-CO-10000013